# Generated by Django 6.0.6 on 2026-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=20)),
                ('P_price', models.IntegerField()),
                ('P_Description', models.IntegerField(max_length=50)),
            ],
        ),
    ]
