# Generated by Django 6.0.6 on 2026-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_Description',
            field=models.CharField(max_length=50),
        ),
    ]
