# Generated by Django 6.0.6 on 2026-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_p_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='P_quantity',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
